### ISSUE TITLE
Add Server Side Rendering

### ISSUE THREAD

**Issue by Lith** [scaleflex/ng-cloudimage-responsive#15]
Hello,

We use Angular Universal (v9) for server-side rendering (better performance and SEO) but the plugin doesn't works server-side (only client side).

Could you add this feature ?
Could we have an estimation date about the development for this feature ?

Thanks for your help !

**Comment by dzmitry-stramavus** [comment]
hey @Lith ,

done in **v2.1.1**

**Comment by Lith** [comment]
Hi @dzmitry-stramavus !

Thanks for the update :) 
It works great except one things :  image keep blurred in SSR

Step to reproduce :
- Disable javascript and load the website

I will send to your support our new development url.

Thanks !

**Comment by dzmitry-stramavus** [comment]
hey @Lith ,

The best option is to not show images at all during SSR, since there is no possibility to detect the correct width/height of an image on the server (there is no window object). [you can use this param for it](https://github.com/scaleflex/ng-cloudimage-responsive#emptyonssr)

is it a requirement to show images if js is disabled on the client's browser?
